# Generated by Django 4.1.5 on 2023-01-21 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0007_ca_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CA', 'CA Certificate'), ('srv', 'Server Certificate'), ('agnt', 'Agent Certificate'), ('csr', "Agent's CSR")], max_length=4, verbose_name='Certificte')),
                ('countryName', models.CharField(blank=True, max_length=100, null=True)),
                ('C', models.CharField(blank=True, max_length=100, null=True)),
                ('stateOrProvinceName', models.CharField(blank=True, max_length=100, null=True)),
                ('ST', models.CharField(blank=True, max_length=100, null=True)),
                ('localityName', models.CharField(blank=True, max_length=100, null=True)),
                ('L', models.CharField(blank=True, max_length=100, null=True)),
                ('organizationName', models.CharField(blank=True, max_length=100, null=True)),
                ('O', models.CharField(blank=True, max_length=100, null=True)),
                ('organizationalUnitName', models.CharField(blank=True, max_length=100, null=True)),
                ('OU', models.CharField(blank=True, max_length=100, null=True)),
                ('commonName', models.CharField(blank=True, max_length=100, null=True)),
                ('CN', models.CharField(blank=True, max_length=100, null=True)),
                ('emailAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('public_key_txt', models.TextField(blank=True, null=True)),
                ('serial_number', models.IntegerField(blank=True, max_length=8, null=True)),
                ('notAfter', models.DateTimeField(blank=True, null=True)),
                ('notBefore', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mgmt.agent')),
            ],
        ),
        migrations.DeleteModel(
            name='CA',
        ),
    ]
