# Generated by Django 4.1.5 on 2023-01-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0008_cartificate_delete_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartificate',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
