# Generated by Django 4.1.5 on 2023-01-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0009_alter_cartificate_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ou',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subortinate', to='mgmt.ou'),
        ),
    ]
