# Generated by Django 4.1.5 on 2023-01-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0010_alter_ou_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ou',
            name='parent',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subortinate', to='mgmt.ou'),
        ),
    ]
