# Generated by Django 4.1.5 on 2023-01-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0011_alter_ou_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Emp',
            field=models.ForeignKey(blank=True, help_text='Agents owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned', to='mgmt.emp'),
        ),
    ]
