# Generated by Django 4.1.5 on 2023-01-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_alter_ou_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='Email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Employee email'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Employee phone'),
        ),
        migrations.AlterField(
            model_name='ou',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ou',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subortinate', to='mgmt.ou'),
        ),
    ]
