name: Buld-oZTes-Docker-Container
on:
  push:
    branches: 
    - main
    paths:
      - oztes/**
      - Dockerfile
      - requirements.txt
jobs:

  docker-buld-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - id: docker-publish
      name: Build image
      uses: bitovi/github-actions-docker-publish@v1.0.3
      with:
        docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
        docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
        checkout: 'false'
        image_tag: 'latest'
        #sha: 'true' # won't do anything since image_tag is set
        org_name: 'srtkkv'
        repo_name: 'oztes'
        #build_args: --build-arg git_personal_token=PAT_token
        working-directory: .
    - run: |
        echo "Image Created:  ${{ env.image }}"
        echo "Tag Created: ${{ env.tag }}"
  deploy-test-env:
    needs: docker-buld-push
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          ENVIRONMENT: test
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop oztes
            docker run -d --rm --name oztes -p 9000:8000 -e DB_HOST=${{ secrets.DB_TEST_HOST }} -e DB_NAME=${{ secrets.DB_TEST_NAME }} -e DB_USER=${{ secrets.DB_TEST_USER }} -e DB_PASS=${{ secrets.DB_TEST_PASS }} srtkkv/oztes:latest  

